#mips-openwrt-linux-uclibc-gcc -g -o tcp_Server3 tcp_Server.c -lpthread
gcc -g -o tcp_Server2 tcp_Server.c -lpthread
#mips-openwrt-linux-uclibc-gcc -g -o tcp_Client tcp_Client.c
gcc -g -o tcp_Client tcp_Client.c
