cc -g -o FIFO2 FIFO.c
cc -g -o Reader Reader.c
cc -g -o FIFO_open FIFO_open.c

# co the viet lenh thuc thi tren terminal hoac dung cach sau:
# C2: them dau & sau cau lenh thuc thi dau tien -> thuc hien 2 cau lenh 'dong thoi'? 
# (chinh xac, OS co the thuc hien ngau nhien mot trong 2 file nay)
# con neu khong -> thuc hien lan luot: het lenh trong file1 -> file2
#./Reader &
#./FIFO2


